### ISSUE TITLE
关于selectPicker 在columns异步耗时操作的时候，在modelValue监听去设置showValue，并不是太合理，会出现showValue为空的情况

### ISSUE THREAD

**Issue by BeginnerDone** [Moonofweisheng/wot-design-uni#167]
### Wot Design Uni 版本号

0.2.13

### 平台

h5, 微信小程序

### 重现链接

https://wot-design-uni.cn/component/select-picker.html

### 重现步骤

columns通过异步耗时请求设置的时候。v-model绑定了值，但是其回显的值并没有出现。
原因是监听modelValue的时候，columns还没有返回，而这个时候setShowValue，所以showValue为空了。
建议通过computed计算的方式返回showValue，比较好点。

### 期望的结果是什么？

columns通过耗时操作设置的时候，依然显示showValue

### 实际的结果是什么？

耗时操作之后，showValue为空

### 其他补充信息

建议这个问题能快点修复一下，谢谢了

**Comment by BeginnerDone** [comment]
colPicker也是同样的问题

**Comment by BeginnerDone** [comment]
大佬，这个能修复吗。

**Comment by Moonofweisheng** [comment]
昨天有在看，不过不太清楚你具体产生问题的场景，提供一下复现demo把，我用来调试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月24日(星期三) 下午4:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] 关于selectPicker 在columns异步耗时操作的时候，在modelValue监听去设置showValue，并不是太合理，会出现showValue为空的情况 (Issue #167)





 
大佬，这个能修复吗。

**Comment by BeginnerDone** [comment]
> 昨天有在看，不过不太清楚你具体产生问题的场景，提供一下复现demo把，我用来调试。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Moonofweisheng/wot-design-uni" ***@***.***&gt;; 发送时间:&nbsp;2024年1月24日(星期三) 下午4:12 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] 关于selectPicker 在columns异步耗时操作的时候，在modelValue监听去设置showValue，并不是太合理，会出现showValue为空的情况 (Issue #167) 大佬，这个能修复吗。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

场景很简单比如，一个表单，在onLoad 中 selectPicker 的columns数据是通过接口或者延时进行添加数据的，延时可以设置长一点。在columns还没有返回的时候，依然是空的时候，就通过v-model绑定selectPicker 的值的时候，他是不回填的。

**Comment by Moonofweisheng** [comment]
可以给出一个复现demo出来。附件在当前issue就行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月24日(星期三) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] 关于selectPicker 在columns异步耗时操作的时候，在modelValue监听去设置showValue，并不是太合理，会出现showValue为空的情况 (Issue #167)





  
昨天有在看，不过不太清楚你具体产生问题的场景，提供一下复现demo把，我用来调试。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Moonofweisheng/wot-design-uni" @.&gt;; 发送时间:&nbsp;2024年1月24日(星期三) 下午4:12 @.&gt;; @.&gt;; 主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] 关于selectPicker 在columns异步耗时操作的时候，在modelValue监听去设置showValue，并不是太合理，会出现showValue为空的情况 (Issue #167) 大佬，这个能修复吗。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
场景很简单比如，一个表单，在onLoad 中 selectPicker 的columns数据是通过接口或者延时进行添加数据的，延时可以设置长一点。在columns还没有返回的时候，依然是空的时候，就通过v-model绑定selectPicker 的值的时候，他是不回填的。

**Comment by BeginnerDone** [comment]
[demo.zip](https://github.com/Moonofweisheng/wot-design-uni/files/14035904/demo.zip)
