### ISSUE TITLE
themeVars 修改主题色 按钮颜色未变

### ISSUE THREAD

**Issue by jamarion126** [Moonofweisheng/wot-design-uni#174]
### Wot Design Uni 版本号

0.2.21

### 平台

h5

### 重现链接

无

### 重现步骤

const themeVars = reactive({
  "color-theme": "purple",
});

 <wd-config-provider :theme-vars="themeVars">
<wd-button
            type="primary"
          >
           LOGIN
          </wd-button>
  </wd-config-provider>

### 期望的结果是什么？

按钮颜色变色

### 实际的结果是什么？

颜色未变

**Comment by Moonofweisheng** [comment]
按钮并未应用主题色，请直接修改按钮颜色




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月1日(星期四) 下午2:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Moonofweisheng/wot-design-uni] themeVars 修改主题色 按钮颜色未变 (Issue #174)





 
Wot Design Uni 版本号
 
0.2.21
 
平台
 
h5
 
重现链接
 
无
 
重现步骤
 
const themeVars = reactive({
 "color-theme": "purple",
 });
              LOGIN               
期望的结果是什么？
 
按钮颜色变色
 
实际的结果是什么？
 
颜色未变
 
环境信息
 
No response
 
其他补充信息
 
No response

**Comment by jamarion126** [comment]
> 按钮感应应用主题颜色，请直接修改按钮颜色
> [……](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Moonofweisheng/wot-design-uni" ***@***.***&gt;; 发送时间:&nbsp;2024年2月1日(星期四) 下午2:19 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Moonofweisheng/wot-design-uni] themeVars 修改主题色 按钮颜色未变 (Issue #174) Wot Design Uni 版本号 0.2.21 平台 h5 重现链接 无 重现步骤 const themeVars = reactive({ "color-theme": "purple", }); LOGIN 期望的结果是什么？ 按钮颜色变色 实际的结果是什么？ 颜色未变 环境信息 No response 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

那是否还有其他组件跟按钮一样，没有应用主题色

**Comment by Moonofweisheng** [comment]
可以看下代码，例如tabs、sort等组件，都是使用了渐变色，需要自己指定颜色。不过1.0版本会支持css变量指定主色，预计年后发版



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月1日(周四) 下午2:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] themeVars 修改主题色 按钮颜色未变 (Issue #174)




  
按钮感应应用主题颜色，请直接修改按钮颜色
 ……
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Moonofweisheng/wot-design-uni" @.&gt;; 发送时间:&nbsp;2024年2月1日(星期四) 下午2:19 @.&gt;; @.&gt;; 主题:&nbsp;[Moonofweisheng/wot-design-uni] themeVars 修改主题色 按钮颜色未变 (Issue #174) Wot Design Uni 版本号 0.2.21 平台 h5 重现链接 无 重现步骤 const themeVars = reactive({ "color-theme": "purple", }); LOGIN 期望的结果是什么？ 按钮颜色变色 实际的结果是什么？ 颜色未变 环境信息 No response 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
那是否还有其他组件跟按钮一样，没有应用主题色
