### ISSUE TITLE
wd-upload 在ios 系统上（iphone）上打不开选择文件的对话框 ，无效

### ISSUE THREAD

**Issue by BeginnerDone** [Moonofweisheng/wot-design-uni#227]
### Wot Design Uni 版本号

1.2.12

### 平台

微信小程序

### 重现链接

https://wot-design-uni.gitee.io/component/upload.html

### 重现步骤

使用iphone 打开wot-design-uni微信小程序 upload组件

### 期望的结果是什么？

打开，上传图片

### 实际的结果是什么？

没有反应

**Comment by BeginnerDone** [comment]
那这个定位到问题了，该怎么办呢，你这边要不要抛出一个参数来控制sourceType是否传递呢？

**Comment by Moonofweisheng** [comment]
sourceType只要传了，无论传什么都不行，是吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月8日(星期一) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Moonofweisheng/wot-design-uni] wd-upload 在ios 系统上（iphone）上打不开选择文件的对话框 ，无效 (Issue #227)














 
那这个定位到问题了，该怎么办呢，你这边要不要抛出一个参数来控制sourceType是否传递呢？

**Comment by BeginnerDone** [comment]
> sourceType只要传了，无论传什么都不行，是吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年4月8日(星期一) 下午5:54 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] wd-upload 在ios 系统上（iphone）上打不开选择文件的对话框 ，无效 (Issue #227) 那这个定位到问题了，该怎么办呢，你这边要不要抛出一个参数来控制sourceType是否传递呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

具体没测，我待会测试下看看，另外我看Dcloud官网上 微信小程序从基础库 2.21.0 开始， [wx.chooseImage](https://developers.weixin.qq.com/miniprogram/dev/api/media/image/wx.chooseImage.html) 停止维护，请使用 [uni.chooseMedia](https://uniapp.dcloud.net.cn/api/media/video.html#choosemedia) 代替。不知道是不是替换就没有这个·问题了，后面我会测试下看看。

**Comment by Moonofweisheng** [comment]
感谢，如果传[]或者传null可以避免这个问题的话，可以调整props的类型支持兼容这个问题，如果不行的话就只能在微信小程序平台调整API到chooseMedia了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月8日(星期一) 晚上6:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Moonofweisheng/wot-design-uni] wd-upload 在ios 系统上（iphone）上打不开选择文件的对话框 ，无效 (Issue #227)














  
sourceType只要传了，无论传什么都不行，是吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年4月8日(星期一) 下午5:54 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] wd-upload 在ios 系统上（iphone）上打不开选择文件的对话框 ，无效 (Issue #227) 那这个定位到问题了，该怎么办呢，你这边要不要抛出一个参数来控制sourceType是否传递呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
具体没测，我待会测试下看看，另外我看Dcloud官网上 微信小程序从基础库 2.21.0 开始， wx.chooseImage 停止维护，请使用 uni.chooseMedia 代替。不知道是不是替换就没有这个·问题了，后面我会测试下看看。

**Comment by BeginnerDone** [comment]
> 感谢，如果传[]或者传null可以避免这个问题的话，可以调整props的类型支持兼容这个问题，如果不行的话就只能在微信小程序平台调整API到chooseMedia了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年4月8日(星期一) 晚上6:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] wd-upload 在ios 系统上（iphone）上打不开选择文件的对话框 ，无效 (Issue #227) sourceType只要传了，无论传什么都不行，是吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年4月8日(星期一) 下午5:54 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] wd-upload 在ios 系统上（iphone）上打不开选择文件的对话框 ，无效 (Issue #227) 那这个定位到问题了，该怎么办呢，你这边要不要抛出一个参数来控制sourceType是否传递呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 具体没测，我待会测试下看看，另外我看Dcloud官网上 微信小程序从基础库 2.21.0 开始， wx.chooseImage 停止维护，请使用 uni.chooseMedia 代替。不知道是不是替换就没有这个·问题了，后面我会测试下看看。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

必须为`sourceType `显式的指定值`:sourceType="['camera','album']"` 或者其中一个方式就没问题了，反正就是不能默认[ ]，我们这边如果不传值，你那边是默认传递[ ]，但是对于uniapp 怎么处理你传递的[ ] 就不知道了，github上没找到这部分源码 ，所以是否可以你那边就直接默认['camera','album']，因为就Dcloud 上的而言，他如果不传，默认就是['camera','album']。

**Comment by Moonofweisheng** [comment]
这个方案也可以，我确认后调整。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月8日(周一) 晚上6:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] wd-upload 在ios 系统上（iphone）上打不开选择文件的对话框 ，无效 (Issue #227)




  
感谢，如果传[]或者传null可以避免这个问题的话，可以调整props的类型支持兼容这个问题，如果不行的话就只能在微信小程序平台调整API到chooseMedia了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年4月8日(星期一) 晚上6:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] wd-upload 在ios 系统上（iphone）上打不开选择文件的对话框 ，无效 (Issue #227) sourceType只要传了，无论传什么都不行，是吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2024年4月8日(星期一) 下午5:54 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] wd-upload 在ios 系统上（iphone）上打不开选择文件的对话框 ，无效 (Issue #227) 那这个定位到问题了，该怎么办呢，你这边要不要抛出一个参数来控制sourceType是否传递呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 具体没测，我待会测试下看看，另外我看Dcloud官网上 微信小程序从基础库 2.21.0 开始， wx.chooseImage 停止维护，请使用 uni.chooseMedia 代替。不知道是不是替换就没有这个·问题了，后面我会测试下看看。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
必须为sourceType 显式的指定值:sourceType="['camera','album']" 或者其中一个方式就没问题了，反正就是不能默认[ ]，我们这边如果不传值，你那边是默认传递[ ]，但是对于uniapp 怎么处理你传递的[ ] 就不知道了，github上没找到这部分源码 ，所以是否可以你那边就直接默认['camera','album']，因为就Dcloud 上的而言，他如果不传，默认就是['camera','album']。

**Comment by BeginnerDone** [comment]
好的，感谢
