### ISSUE TITLE
upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。

### ISSUE THREAD

**Issue by BeginnerDone** [Moonofweisheng/wot-design-uni#261]
### 这个功能解决了什么问题？

自定义压缩file文件

### 你期望的 API 是什么样子的？

`<wd-upload action="https://ftf.jd.com/api/uploadImg" :file-compress="fileCompress"></wd-upload>`

```
function fileCompress({file,resolve}){
   // 执行压缩操作，改变file
   .......
   resolve(newFile)
}
```

**Comment by Moonofweisheng** [comment]
是小程序平台吗，目前没有了解到有什么方法可以在chooseImage和uoloadFile方法之间做一个压缩的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月25日(周四) 上午10:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261)




 
这个功能解决了什么问题？
 
自定义压缩file文件
 
你期望的 API 是什么样子的？
 
<wd-upload action="https://ftf.jd.com/api/uploadImg" :file-compress="fileCompress"&gt;</wd-upload&gt;
 function fileCompress({file,resolve}){    // 执行压缩操作，改变file    .......    resolve(newFile) }

**Comment by BeginnerDone** [comment]
> 是小程序平台吗，目前没有了解到有什么方法可以在chooseImage和uoloadFile方法之间做一个压缩的。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月25日(周四) 上午10:30 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 这个功能解决了什么问题？ 自定义压缩file文件 你期望的 API 是什么样子的？ <wd-upload action="https://ftf.jd.com/api/uploadImg" :file-compress="fileCompress"&gt;</wd-upload&gt; function fileCompress({file,resolve}){ // 执行压缩操作，改变file ....... resolve(newFile) } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

是小程序端，现在是通过canvas尺寸改变来压缩的。

**Comment by BeginnerDone** [comment]
> 是小程序平台吗，目前没有了解到有什么方法可以在chooseImage和uoloadFile方法之间做一个压缩的。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月25日(周四) 上午10:30 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 这个功能解决了什么问题？ 自定义压缩file文件 你期望的 API 是什么样子的？ <wd-upload action="https://ftf.jd.com/api/uploadImg" :file-compress="fileCompress"&gt;</wd-upload&gt; function fileCompress({file,resolve}){ // 执行压缩操作，改变file ....... resolve(newFile) } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

主要就是想是否可以提供一个可以操作这个file的一个函数。

**Comment by Moonofweisheng** [comment]
那试试在before-upload做个处理呢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月25日(周四) 上午10:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261)




  
是小程序平台吗，目前没有了解到有什么方法可以在chooseImage和uoloadFile方法之间做一个压缩的。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月25日(周四) 上午10:30 收件人: @.&gt;; 抄送: @.&gt;; 主题: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 这个功能解决了什么问题？ 自定义压缩file文件 你期望的 API 是什么样子的？ <wd-upload action="https://ftf.jd.com/api/uploadImg" :file-compress="fileCompress"&gt;</wd-upload&gt; function fileCompress({file,resolve}){ // 执行压缩操作，改变file ....... resolve(newFile) } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
是小程序端，现在是通过canvas尺寸改变来压缩的。

**Comment by BeginnerDone** [comment]
> 那试试在before-upload做个处理呢。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月25日(周四) 上午10:47 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 是小程序平台吗，目前没有了解到有什么方法可以在chooseImage和uoloadFile方法之间做一个压缩的。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月25日(周四) 上午10:30 收件人: @.&gt;; 抄送: @.&gt;; 主题: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 这个功能解决了什么问题？ 自定义压缩file文件 你期望的 API 是什么样子的？ <wd-upload action="https://ftf.jd.com/api/uploadImg" :file-compress="fileCompress"&gt;</wd-upload&gt; function fileCompress({file,resolve}){ // 执行压缩操作，改变file ....... resolve(newFile) } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 是小程序端，现在是通过canvas尺寸改变来压缩的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

是的，我觉得在beforeUpload最合适，可是目前我看beforeUpload之resolve一个boolean值，并没有可以操作改变file的。


```
  beforeUpload({
            files,
            fileList: uploadFiles.value,
            resolve: (isPass: boolean) => {
              isPass && mapFiles(files)
            }
 })
```

**Comment by BeginnerDone** [comment]
> 那试试在before-upload做个处理呢。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月25日(周四) 上午10:47 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 是小程序平台吗，目前没有了解到有什么方法可以在chooseImage和uoloadFile方法之间做一个压缩的。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月25日(周四) 上午10:30 收件人: @.&gt;; 抄送: @.&gt;; 主题: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 这个功能解决了什么问题？ 自定义压缩file文件 你期望的 API 是什么样子的？ <wd-upload action="https://ftf.jd.com/api/uploadImg" :file-compress="fileCompress"&gt;</wd-upload&gt; function fileCompress({file,resolve}){ // 执行压缩操作，改变file ....... resolve(newFile) } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 是小程序端，现在是通过canvas尺寸改变来压缩的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

所以，是否可以考虑在beforeUpload中resolve，多一个额外file的参数。

**Comment by Moonofweisheng** [comment]
OK，那这个可以提供。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月25日(周四) 上午10:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261)




  
那试试在before-upload做个处理呢。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月25日(周四) 上午10:47 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 是小程序平台吗，目前没有了解到有什么方法可以在chooseImage和uoloadFile方法之间做一个压缩的。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月25日(周四) 上午10:30 收件人: @.&gt;; 抄送: @.&gt;; 主题: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 这个功能解决了什么问题？ 自定义压缩file文件 你期望的 API 是什么样子的？ <wd-upload action="https://ftf.jd.com/api/uploadImg" :file-compress="fileCompress"&gt;</wd-upload&gt; function fileCompress({file,resolve}){ // 执行压缩操作，改变file ....... resolve(newFile) } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 是小程序端，现在是通过canvas尺寸改变来压缩的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
是的，我觉得在beforeUpload最合适，可是目前我看beforeUpload之resolve一个boolean值，并没有可以操作改变file的。
   beforeUpload({             files,             fileList: uploadFiles.value,             resolve: (isPass: boolean) =&gt; {               isPass &amp;&amp; mapFiles(files)             }  })

**Comment by BeginnerDone** [comment]
> OK，那这个可以提供。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年4月25日(周四) 上午10:50 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 那试试在before-upload做个处理呢。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月25日(周四) 上午10:47 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 是小程序平台吗，目前没有了解到有什么方法可以在chooseImage和uoloadFile方法之间做一个压缩的。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年4月25日(周四) 上午10:30 收件人: @.&gt;; 抄送: @.&gt;; 主题: [Moonofweisheng/wot-design-uni] upload 能否增加一个对于file 处理的一个函数，比如自定义压缩这个file的处理，或者提供一个自定义request，我们可以自定义上传方法。 (Issue #261) 这个功能解决了什么问题？ 自定义压缩file文件 你期望的 API 是什么样子的？ <wd-upload action="https://ftf.jd.com/api/uploadImg" :file-compress="fileCompress"&gt;</wd-upload&gt; function fileCompress({file,resolve}){ // 执行压缩操作，改变file ....... resolve(newFile) } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 是小程序端，现在是通过canvas尺寸改变来压缩的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 是的，我觉得在beforeUpload最合适，可是目前我看beforeUpload之resolve一个boolean值，并没有可以操作改变file的。 beforeUpload({ files, fileList: uploadFiles.value, resolve: (isPass: boolean) =&gt; { isPass &amp;&amp; mapFiles(files) } }) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

感谢！
