### ISSUE TITLE
wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空

### ISSUE THREAD

**Issue by Hlf-jackson** [Moonofweisheng/wot-design-uni#429]
### Wot Design Uni 版本号

1.2.28

### 平台

微信小程序

### 复现Demo地址

无

### 重现步骤

<wd-picker
            :columns="types"
            label-key="text"
            value-key="value"
            v-model="addFormData.type"
            @confirm="handleType($event, 'type')"
          />，types为进入页面时接口获取的数组

### 期望的结果是什么？

进入组件，不滑动筛选，点击保存能选中默认的第一条数据

### 实际的结果是什么？

实际$event返回的value和selectedItems都是空的

### 环境信息

uniapp 微信小程序

**Comment by Moonofweisheng** [comment]
可以试试查到数据再渲染组件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月10日(周三) 晚上9:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Moonofweisheng/wot-design-uni] wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空 (Issue #429)




 
Wot Design Uni 版本号
 
1.2.28
 
平台
 
微信小程序
 
复现Demo地址
 
无
 
重现步骤
 
<wd-picker
 :columns="types"
 label-key="text"
 value-key="value"
 v-model="addFormData.type"
 @confirm="handleType($event, 'type')"
 /&gt;，types为进入页面时接口获取的数组
 
期望的结果是什么？
 
进入组件，不滑动筛选，点击保存能选中默认的第一条数据
 
实际的结果是什么？
 
实际$event返回的value和selectedItems都是空的
 
环境信息
 
uniapp 微信小程序
 
其他补充信息
 
No response

**Comment by Hlf-jackson** [comment]
> 可以试试查到数据再渲染组件
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月10日(周三) 晚上9:24 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Moonofweisheng/wot-design-uni] wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空 (Issue #429) Wot Design Uni 版本号 1.2.28 平台 微信小程序 复现Demo地址 无 重现步骤 <wd-picker :columns="types" label-key="text" value-key="value" v-model="addFormData.type" @confirm="handleType($event, 'type')" /&gt;，types为进入页面时接口获取的数组 期望的结果是什么？ 进入组件，不滑动筛选，点击保存能选中默认的第一条数据 实际的结果是什么？ 实际$event返回的value和selectedItems都是空的 环境信息 uniapp 微信小程序 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;



> 可以尝试查询数据再
> […](#)
> ---原始邮件--- 发件人：***@***.***>发送时间：2024年7月10日(周三)晚上9:24 收件人：***@***.***>;抄送：***@***.***>;主题: [Moonofweisheng/wot-design-uni] wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空 (Issue #429 ) Wot Design Uni 版本号 1.2.28 平台微信小程序 复现Demo地址 无 重现步骤 <wd-picker :columns="types" label-key="text" value-key="value" v-model="addFormData.type" @ confirmed ="handleType($event, 'type')" />，types为进入页面接口时获取的数组预期的结果是什么？ 进入组件，不滑动筛选，点击保存能选中默认的第一个条数据 实际实际$event返回的值和selectedItems都是空的环境信息uniapp微信小程序其他补充信息无回复 — 直接回复此邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您订阅了此主题。消息 ID：***@***.***>

肯定是查到数据了呀，打开下拉框的时候是能看到数据的，就是第一次只要不操作直接点击确定是选不到值的，只要随便往下拉选一个是可以选到值的

**Comment by Moonofweisheng** [comment]
> > 可以试试查到数据再渲染组件
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年7月10日(周三) 晚上9:24 收件人: _**@**_.**_>; 抄送: _**@**_._**>; 主题: [Moonofweisheng/wot-design-uni] wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空 (Issue #429) Wot Design Uni 版本号 1.2.28 平台 微信小程序 复现Demo地址 无 重现步骤 <wd-picker :columns="types" label-key="text" value-key="value" v-model="addFormData.type" @confirm="handleType($event, 'type')" />，types为进入页面时接口获取的数组 期望的结果是什么？ 进入组件，不滑动筛选，点击保存能选中默认的第一条数据 实际的结果是什么？ 实际$event返回的value和selectedItems都是空的 环境信息 uniapp 微信小程序 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> > 可以尝试查询数据再
> > […](#)
> > ---原始邮件--- 发件人：_**@**_._**>发送时间：2024年7月10日(周三)晚上9:24 收件人：**_@_**.**_>;抄送：_**@**_._**>;主题: [Moonofweisheng/wot-design-uni] wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空 (Issue #429 ) Wot Design Uni 版本号 1.2.28 平台微信小程序 复现Demo地址 无 重现步骤 <wd-picker :columns="types" label-key="text" value-key="value" v-model="addFormData.type" @ confirmed ="handleType($event, 'type')" />，types为进入页面接口时获取的数组预期的结果是什么？ 进入组件，不滑动筛选，点击保存能选中默认的第一个条数据 实际实际$event返回的值和selectedItems都是空的环境信息uniapp微信小程序其他补充信息无回复 — 直接回复此邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您订阅了此主题。消息 ID：**_@_**.**_>
> 
> 肯定是查到数据了呀，打开下拉框的时候是能看到数据的，就是第一次只要不操作直接点击确定是选不到值的，只要随便往下拉选一个是可以选到值的

我的意思是查到数据前，不要渲染picker试试，如果还不行可以提供一个复现demo给我。

**Comment by Hlf-jackson** [comment]
> > > 可以试试查到数据再渲染组件
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年7月10日(周三) 晚上9:24 收件人: _**@**_.**_>; 抄送: _**@**_._**>; 主题: [Moonofweisheng/wot-design-uni] wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空 (Issue #429) Wot Design Uni 版本号 1.2.28 平台 微信小程序 复现Demo地址 无 重现步骤 <wd-picker :columns="types" label-key="text" value-key="value" v-model="addFormData.type" @confirm="handleType($event, 'type')" />，types为进入页面时接口获取的数组 期望的结果是什么？ 进入组件，不滑动筛选，点击保存能选中默认的第一条数据 实际的结果是什么？ 实际$event返回的value和selectedItems都是空的 环境信息 uniapp 微信小程序 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> > 
> > 
> > > 可以尝试查询数据再
> > > […](#)
> > > ---原始邮件--- 发件人：_**@**_._**>发送时间：2024年7月10日(周三)晚上9:24 收件人：**_@_**.**_>;抄送：_**@**_._**>;主题: [Moonofweisheng/wot-design-uni] wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空 (Issue #429 ) Wot Design Uni 版本号 1.2.28 平台微信小程序 复现Demo地址 无 重现步骤 <wd-picker :columns="types" label-key="text" value-key="value" v-model="addFormData.type" @ confirmed ="handleType($event, 'type')" />，types为进入页面接口时获取的数组预期的结果是什么？ 进入组件，不滑动筛选，点击保存能选中默认的第一个条数据 实际实际$event返回的值和selectedItems都是空的环境信息uniapp微信小程序其他补充信息无回复 — 直接回复此邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您订阅了此主题。消息 ID：**_@_**.**_>
> > 
> > 
> > 肯定是查到数据了呀，打开下拉框的时候是能看到数据的，就是第一次只要不操作直接点击确定是选不到值的，只要随便往下拉选一个是可以选到值的
> 
> 我的意思是查到数据前，不要渲染picker试试，如果还不行可以提供一个复现demo给我。

这样子是解决了，用v-if 数据，但是ui里不能直接优化这方面的嘛

**Comment by Moonofweisheng** [comment]
微信插槽即使不显示也会执行相关逻辑，这个是微信的bug，你可以看下常见问题里面有介绍，目前看没什么好办法。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月11日(星期四) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空 (Issue #429)





    
可以试试查到数据再渲染组件
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年7月10日(周三) 晚上9:24 收件人: _@**._&gt;; 抄送: ***@***.***&gt;; 主题: [Moonofweisheng/wot-design-uni] wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空 (Issue #429) Wot Design Uni 版本号 1.2.28 平台 微信小程序 复现Demo地址 无 重现步骤 <wd-picker :columns="types" label-key="text" value-key="value" v-model="addFormData.type" @confirm="handleType($event, 'type')" /&gt;，types为进入页面时接口获取的数组 期望的结果是什么？ 进入组件，不滑动筛选，点击保存能选中默认的第一条数据 实际的结果是什么？ 实际$event返回的value和selectedItems都是空的 环境信息 uniapp 微信小程序 其他补充信息 No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.**_&gt;
   
可以尝试查询数据再
 …
 ---原始邮件--- ***@***.***&gt;发送时间：2024年7月10日(周三)晚上9:24 ***@***.******@***.***&gt;;主题: [Moonofweisheng/wot-design-uni] wd-picker组件异步数据，进入页面后第一次打开组件，默认confirm无法选到取值，value, selectedItems都为空 (Issue #429 ) Wot Design Uni 版本号 1.2.28 平台微信小程序 复现Demo地址 无 重现步骤 <wd-picker :columns="types" label-key="text" value-key="value" v-model="addFormData.type" @ confirmed ="handleType($event, 'type')" /&gt;，types为进入页面接口时获取的数组预期的结果是什么？ 进入组件，不滑动筛选，点击保存能选中默认的第一个条数据 实际实际$event返回的值和selectedItems都是空的环境信息uniapp微信小程序其他补充信息无回复 — 直接回复此邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您订阅了此主题。消息 ***@***.***&gt;
  
肯定是查到数据了呀，打开下拉框的时候是能看到数据的，就是第一次只要不操作直接点击确定是选不到值的，只要随便往下拉选一个是可以选到值的
  
我的意思是查到数据前，不要渲染picker试试，如果还不行可以提供一个复现demo给我。
  
这样子是解决了，用v-if 数据，但是ui里不能直接优化这方面的嘛

**Comment by Moonofweisheng** [comment]
参考这一点：https://wot-design-uni.pages.dev/guide/common-problems.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%9C%A8%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E4%B8%8A%E4%BD%BF%E7%94%A8popup%E3%80%81actionsheet%E3%80%81dropdownitem%E7%AD%89%E5%BC%B9%E5%87%BA%E6%A1%86%E7%BB%84%E4%BB%B6%E5%8C%85%E8%A3%B9slider%E3%80%81tabs%E7%AD%89%E7%BB%84%E4%BB%B6%E6%97%B6-slider%E3%80%81tabs%E8%A1%A8%E7%8E%B0%E5%BC%82%E5%B8%B8
