### ISSUE TITLE
[Bug 上报] wd-upload 当自动上传为false 时 v-model:file-list 失效 change 事件不会触发

### ISSUE THREAD

**Issue by wangkewei666** [Moonofweisheng/wot-design-uni#580]
### Wot Design Uni 版本号

1.3.8

### 平台

APP

### 复现Demo地址（如不提供，issue将被直接关闭）

https://github.com/wangkewei666/-wdupload.git

### 重现步骤

 wd-upload  组件将 auto-upload 设置为false 
APP中 拍照 相册选着图片
change事件 和 双向数据绑定的list 无法触发

### 期望的结果是什么？

实现auto-upload 设置为false  
change事件 和 双向数据绑定的list 可用

### 实际的结果是什么？

无响应事件

### 环境信息

wot-design-uni 1.3.8 
app ios 17.6.1
HBuilderX4.08
ios13 pro

**Comment by 1120158440** [comment]
如果没有自动上传  change事件没有触发  
![image](https://github.com/user-attachments/assets/d18ada01-f644-4a00-bb76-23487a939ca7)

**Comment by Moonofweisheng** [comment]
手动调用submit方法后才会有相应的事件触发。

![image](https://github.com/user-attachments/assets/b3ce9830-38f0-4a06-86bf-18e470aee05d)

**Comment by 1120158440** [comment]
大佬&nbsp;
手动调用后解决不了我的问题&nbsp; &nbsp;我没有用action 填地址
上传的逻辑是我自己写的
我需要判断 是否有新增的图片 走不同的逻辑&nbsp;
导致 我无法拿到组件里面的图片路径&nbsp;&nbsp;
目前控件action是必填的 正常用应该是可以的&nbsp; &nbsp; &nbsp; action 地址为空&nbsp; &nbsp;自己去实现 就会有问题


我自己也试了 修改&nbsp; 加上else 里面的逻辑就可以了&nbsp;


&nbsp; uploadFiles.value.push(initState)
&nbsp; if (props.autoUpload) {
&nbsp; &nbsp; startUploadFiles()
&nbsp; } else {
&nbsp; &nbsp; // emit('change', { fileList: uploadFiles.value })
&nbsp; &nbsp; // emitFileList()
&nbsp; }






1120158440
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月6日(星期五) 中午1:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-upload 当自动上传为false 时 v-model:file-list 失效 change 事件不会触发 (Issue #580)





 
手动调用submit方法后才会有相应的事件触发。
 
image.png (view on web)

**Comment by Moonofweisheng** [comment]
> 大佬&nbsp; 手动调用后解决不了我的问题&nbsp; &nbsp;我没有用action 填地址 上传的逻辑是我自己写的 我需要判断 是否有新增的图片 走不同的逻辑&nbsp; 导致 我无法拿到组件里面的图片路径&nbsp;&nbsp; 目前控件action是必填的 正常用应该是可以的&nbsp; &nbsp; &nbsp; action 地址为空&nbsp; &nbsp;自己去实现 就会有问题 我自己也试了 修改&nbsp; 加上else 里面的逻辑就可以了&nbsp; &nbsp; uploadFiles.value.push(initState) &nbsp; if (props.autoUpload) { &nbsp; &nbsp; startUploadFiles() &nbsp; } else { &nbsp; &nbsp; // emit('change', { fileList: uploadFiles.value }) &nbsp; &nbsp; // emitFileList() &nbsp; } 1120158440 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Moonofweisheng/wot-design-uni" ***@***.***&gt;; 发送时间:&nbsp;2024年9月6日(星期五) 中午1:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-upload 当自动上传为false 时 v-model:file-list 失效 change 事件不会触发 (Issue #580) 手动调用submit方法后才会有相应的事件触发。 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

自定义上传方法，需要自己通知组件上传完成  

![image](https://github.com/user-attachments/assets/8c00a14f-4a6d-420c-8949-fae23b2475dc)

**Comment by 1120158440** [comment]
这个我会用 
自动上传为false 
组件就不支持 双向数据绑定和 change时间触发了么?

**Comment by 1120158440** [comment]
这个我会用&nbsp; 这些重要你们后面会支持
自动上传为false
组件就不支持 双向数据绑定和 change时间触发了么?


1120158440
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Moonofweisheng/wot-design-uni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月6日(星期五) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-upload 当自动上传为false 时 v-model:file-list 失效 change 事件不会触发 (Issue #580)





  
大佬&nbsp; 手动调用后解决不了我的问题&nbsp; &nbsp;我没有用action 填地址 上传的逻辑是我自己写的 我需要判断 是否有新增的图片 走不同的逻辑&nbsp; 导致 我无法拿到组件里面的图片路径&nbsp;&nbsp; 目前控件action是必填的 正常用应该是可以的&nbsp; &nbsp; &nbsp; action 地址为空&nbsp; &nbsp;自己去实现 就会有问题 我自己也试了 修改&nbsp; 加上else 里面的逻辑就可以了&nbsp; &nbsp; uploadFiles.value.push(initState) &nbsp; if (props.autoUpload) { &nbsp; &nbsp; startUploadFiles() &nbsp; } else { &nbsp; &nbsp; // emit('change', { fileList: uploadFiles.value }) &nbsp; &nbsp; // emitFileList() &nbsp; } 1120158440 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Moonofweisheng/wot-design-uni" @.&gt;; 发送时间:&nbsp;2024年9月6日(星期五) 中午1:40 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Moonofweisheng/wot-design-uni] [Bug 上报] wd-upload 当自动上传为false 时 v-model:file-list 失效 change 事件不会触发 (Issue #580) 手动调用submit方法后才会有相应的事件触发。 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
自定义上传方法，需要自己通知组件上传完成
 
image.png (view on web)

**Comment by Moonofweisheng** [comment]
当文件上传完成后会触发相应的事件，上传前不会。
